# Generated by Django 4.1 on 2022-08-25 17:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=50, null=True)),
                ('tittle', models.CharField(max_length=25, null=True)),
                ('date_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('a', 'active'), ('in', 'inactive')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_type', models.CharField(max_length=22, null=True)),
                ('receipt_date', models.DateTimeField()),
                ('receipt_number', models.BigIntegerField()),
                ('total_amount', models.IntegerField()),
                ('receipt_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='receipts',
            name='account',
        ),
        migrations.RemoveField(
            model_name='receipts',
            name='transaction',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='account_type',
            new_name='account_name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='name',
            new_name='currency',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phonenumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='thirdparty',
            old_name='phone_Number',
            new_name='transaction_cost',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_charge',
            new_name='transaction_code',
        ),
        migrations.RemoveField(
            model_name='account',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='card',
            name='account',
        ),
        migrations.RemoveField(
            model_name='card',
            name='card_name',
        ),
        migrations.RemoveField(
            model_name='card',
            name='card_status',
        ),
        migrations.RemoveField(
            model_name='card',
            name='cvv_security',
        ),
        migrations.RemoveField(
            model_name='card',
            name='date_Issued',
        ),
        migrations.RemoveField(
            model_name='card',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='date',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='guaranter',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loan_balance',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loan_number',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loan_term',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='thirdparty',
            name='name',
        ),
        migrations.RemoveField(
            model_name='thirdparty',
            name='thirdparty_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='original_account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_ref',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='date',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='status',
        ),
        migrations.AddField(
            model_name='account',
            name='account_pin',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='card_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_e', to='wallet.account'),
        ),
        migrations.AddField(
            model_name='card',
            name='card_holder_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_id',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='customer_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='date_reward',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='reward',
            name='transacation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.transaction'),
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='account_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='transaction',
            name='origin_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_a', to='wallet.account'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.account'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='account_pin',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(default=False, max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet'),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_c', to='wallet.account'),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_d', to='wallet.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='destination_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accountb', to='wallet.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
        migrations.DeleteModel(
            name='Receipts',
        ),
        migrations.AddField(
            model_name='receipt',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.transaction'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.receipt'),
        ),
        migrations.AddField(
            model_name='card',
            name='Wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_f', to='wallet.account'),
        ),
        migrations.AddField(
            model_name='card',
            name='date_issued',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='reward',
            name='receipt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.receipt'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='Customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.customer'),
        ),
    ]
