# Generated by Django 4.1 on 2022-08-25 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_notification_receipt_remove_notifications_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
