# Generated by Django 4.1 on 2022-08-25 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_notification_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
