# Generated by Django 4.1 on 2022-08-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_receipt_receipt_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_holder_name',
            field=models.CharField(max_length=27, null=True),
        ),
    ]
