# Generated by Django 4.1 on 2022-08-26 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_alter_card_card_holder_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='date_time',
            new_name='date_of_notification',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='Customer',
            new_name='customer',
        ),
    ]
